### ISSUE TITLE
link to Docker install readme

### ISSUE THREAD

**Issue by Cotswoldsmaker** [spiritumduo/spiritumDuo#31]
https://github.com/spiritumduo/spiritumDuo/blob/da2391b9809a5d2d5364b59bb3a8eee6f0c14ab7/INSTALL.md#L21

**Comment by jcf54** [comment]
Resolved: https://github.com/spiritumduo/spiritumDuo/commit/e1b8f0578f093f654815f93753737a6a1cf2be3d
